on:
  push:
    branches: [ main ]

jobs:
  fixinator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundeo/cfml-ci-tools/cfml-ci-tools:latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run Fixinator
      run: box fixinator
      env:
        FIXINATOR_API_KEY: ${{ secrets.FIXINATOR_API_KEY }}
